
import NavbarAdmin from "@/components/adminHeader";
import SideBarAdmin from "@/components/adminSideBar";
import NavbarManager from "@/components/manageHeader";
import SideBarManager from "@/components/manageSideBar";
import type { Metadata } from "next";
import { Children } from "react";

export const metadata: Metadata = {
    title: "Admin",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <div className="h-screen w-screen flex">          
                <SideBarManager/>                
                <NavbarManager>{children}</NavbarManager>  
                            
            </div>
            {/* <Footer /> */}

        </>

    );
}